### ISSUE TITLE
Make DB config available via environment variables

### ISSUE THREAD

**Issue by n1trux** [jrie/sqstorage#11]
The [mariadb Docker container](https://hub.docker.com/_/mariadb/) uses the following env variables to configure the DB:

```
MYSQL_DATABASE
MYSQL_USER
MYSQL_PASSWORD
```

Would be nice if sqstorage could honor those and configure the DB based on them.

**Comment by jrie** [comment]
Thanks for bringing this up. From what is documented in the mariadb docker container documentation is that the `MYSQL_USER` and `MYSQL_PASSWORD` apply to the `root`user with `all granted` database rights. And I am not sure if this doesn't open another box.

Rather I would prefer creating a database using the above and additionally, in a docker file, create a `user` with only required permissions to the database, which are:
* Data permission
 SELECT, INSERT, UPDATE, DELETE
* Structure
 CREATE, ALTER

Ideally the docker setup would write, one time, all information into [the file](https://github.com/jrie/sqstorage/blob/master/support/dba.php) `/support/dba.php` because its likely that this file never will change after that point and the variables which are currently hardcoded can be reused for `bootDB.php` [(Link)](https://github.com/jrie/sqstorage/blob/master/bootDB.php) to create all required tables on start.

This information are currently:
* User
* Password
* Database and table encoding, in example utf8
* Database host

**Comment by n1trux** [comment]
The env variables mentioned are creating a user with full rights on the DB which is also created. It doesn't apply to the `root` user, there's a separate password (or no password/disabled) for it:

>This user will be granted superuser permissions (see above) **for the database specified** by the `MYSQL_DATABASE` variable.

If you really really don't need the other privileges, just check if the user you've been given has the rights you don't need and let the user drop them:

```
REVOKE DROP ON database.table FROM 'user'@'localhost';
REVOKE EXECUTE ON database.table FROM 'user'@'localhost';
REVOKE GRANT OPTION ON database.table FROM 'user'@'localhost';
REVOKE SHOW DATABASES ON database.table FROM 'user'@'localhost';
FLUSH PRIVILEGES;
```

If you someday do database migrations, you'll probably need `DROP`. You might also like to keep `EXECUTE` in a later stage of the application because you might want to have stored procedures. Or `GRANT OPTION` for read-only cronjob users from the outside. `SHOW DATABASES` doesn't matter because there's only one DB per container in 99% of the cases, although you might want to check if you have that right on non-Docker installations for more security.

You wouldn't want to create DB users from a Dockerfile in a different container than the database.

IMHO there's no harm when you run a docker container to have all rights to a database since no other users would be on said DB and there's nearly no possibility to break out of this apart from a CVE which would make international news.

**Comment by schnoog** [comment]
Hi, are the environment variables available to the php getenv() function in the web servers context?
Could you please start the container and test the following script (call it f.e. test.php place it on the web-root and open it with your browser) 
`
<?php
$ckecks = array('MYSQL_DATABASE','MYSQL_USER','MYSQL_PASSWORD');
foreach($checks as $check){
$tmp = getenv($check);
echo "Read environment variable " .$check ." value:" . $tmp;
}
?>
`
I'll write a patch if all three values are displayed correctly.

**Comment by n1trux** [comment]
>Hi, are the environment variables available to the php getenv() function in the web servers context?

Yes.

**Comment by jrie** [comment]
I think this can be closed, as we have the installation routine taking care of that.

**Comment by n1trux** [comment]
> I think this can be closed, as we have the installation routine taking care of that.

Does the installation routine honor env variables?

**Comment by jrie** [comment]
No, the installation routine does not honor env variables, but during installation all settings are checked accordingly so a smooth installation is done.

**Comment by jrie** [comment]
Added in ada7bbb2b0eab7afcf737ec87fa85eb549e80c93 so that "docker-compose.yml" require a ".env" file like explained in #105 and in "docker-installation.md".
