### ISSUE TITLE
"Zuweisen" in Inventar sollte wohl besser verschieben oder transferieren heissen

### ISSUE THREAD

**Issue by dex2000** [jrie/sqstorage#49]
Wo ich mich dann noch frage, wozu es das transferieren-tab gibt, wenn das in der Kategorieübersicht viel schöner geht... ;)

**Comment by jrie** [comment]
The `/transfer` page was done by request, to be able to quickly move several items in one bulk operation instead of single clicking the "allocate" on the inventory page for every single item.

Also, some time ago the transfer page allowed to set the amount to be transferred from one storage to another in case the amount is greater one. Right now, I am not sure why this feature is not working, but this will be another issue. The code for handling that is in place so and lives in the `/transfer` page.

**Comment by jrie** [comment]
Commit cd2da146ae9afb6010f782507cbcad73b06144fe adds a improved transfer.
1) Items can be split up if amount is not total amount of the item
2) and joined when the exact name of the item exists in the destination storage.
